In [31]:
import numpy as np
b = np.array([[1,2,3,3,1],[6,8,11,10,7]])
print(b.shape)
print (b)
a = np.transpose(b)
print (a)
np.mean(a, axis = 0)

(2, 5)
[[ 1  2  3  3  1]
 [ 6  8 11 10  7]]
[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]


array([2. , 8.4])

In [26]:
average = np.mean(b, axis = 0)
b_centered = b-average
b_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [28]:
v1 = b_centered[0:,0]
v2 = b_centered[0:,1]
b_centered_sp = v1.dot(v2)
print("Скалярное произведение признаков:", b_centered_sp)
N = b_centered.shape[0]
print("b_centered_sp / (N-1) = ", b_centered_sp / (N-1))

Скалярное произведение признаков: 8.0
b_centered_sp / (N-1) =  2.0


In [32]:
import pandas as pd
authors_dict = {
    "author_id": [1, 2, 3],
    "author_name": ["Тургенев", "Чехов", "Островский"]
}
authors = pd.DataFrame(authors_dict)
books_dict = {
    "author_id": [1, 1, 1, 2, 2, 3, 3],
    "book_title": ["Отцы и дети", "Рудин", "Дворянское гнездо", "Толстый и тонкий", "Дама с собачкой", "Гроза", "Таланты и поклонники" ],
    "price": [100, 300, 250, 350, 450, 400, 500]
}
books = pd.DataFrame(books_dict)

print(authors)
print(books)

   author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский
   author_id            book_title  price
0          1           Отцы и дети    100
1          1                 Рудин    300
2          1     Дворянское гнездо    250
3          2      Толстый и тонкий    350
4          2       Дама с собачкой    450
5          3                 Гроза    400
6          3  Таланты и поклонники    500


In [33]:
authors_price = pd.merge(authors, books, on='author_id', how='inner')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    100
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    250
3          2       Чехов      Толстый и тонкий    350
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    400
6          3  Островский  Таланты и поклонники    500

In [34]:
top5 = authors_price.sort_values(by="price", ascending = False).head(5)
top5

author_id author_name            book_title  price
6          3  Островский  Таланты и поклонники    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    400
3          2       Чехов      Толстый и тонкий    350
1          1    Тургенев                 Рудин    300

In [35]:
groupby = authors_price.groupby("author_name")
column_min = groupby.agg({"price": "min"})
column_max = groupby.agg({"price": "max"})
column_mean = groupby["price"].mean()

authors_stat = pd.concat([column_min, column_max, column_mean], axis=1)
authors_stat.columns = ["min_price","max_price","mean_price"]
authors_stat

min_price  max_price  mean_price
author_name                                  
Островский         400        500  450.000000
Тургенев           100        300  216.666667
Чехов              350        450  400.000000